### PR TITLE
Bug fix: use both surface name and field name when filtering for surface field

### LINKED ISSUE #25: Bug fix: use both surface name and field name when filtering for surface field

### PR DESCRIPTION
**Pull request by magland**
Fixes #25

### CODE REVIEW

File: gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx [hunk 1]
```diff
@@ -13,12 +13,12 @@ type Props = {
     height: number
 }
 
-const findGridScalarFieldByName = (data: WorkspaceViewData, name: string) => {
-    return data.gridScalarFields.filter(x => (x.name === name))[0]
+const findGridScalarFieldByName = (data: WorkspaceViewData, name: string, gridName: string) => {
+    return data.gridScalarFields.filter(x => (x.name === name) && (x.gridName === gridName))[0]
```
Comment (magland) [inline gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:17]: Need to use both name and gridName as the filter criteria

File: gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx [hunk 2]
```diff
@@ -13,12 +13,12 @@ type Props = {
...
 }
 
-const findGridVectorFieldByName = (data: WorkspaceViewData, name: string) => {
-    return data.gridVectorFields.filter(x => (x.name === name))[0]
+const findGridVectorFieldByName = (data: WorkspaceViewData, name: string, gridName: string) => {
+    return data.gridVectorFields.filter(x => (x.name === name) && (x.gridName === gridName))[0]
```
Comment (magland) [inline gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:21]: Need to use both name and gridName as the filter criteria

File: gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx [hunk 3]
```diff
@@ -81,8 +82,7 @@ const WorkspaceViewMainWindow: FunctionComponent<Props> = ({data, selection, sel
     const scalarDataRange: [number, number] = useMemo(() => ([vMin, vMax]), [vMin, vMax])
 
     const {svMin, svMax} = useMemo(() => {
-        const names = Object.values(selection.selectedSurfaceScalarFieldNames).filter(a => (a !== undefined)).map(a => (a as string))
-        const scalarFields = names.map(name => (data.surfaceScalarFields.filter(x => (x.name === name))[0]))
+        const scalarFields = data.surfaceScalarFields.filter(x => (selection.selectedSurfaceScalarFieldNames[x.surfaceName]?.includes(x.name)))
```
Comment (magland) [inline gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:85]: Conform to new structure of selectedSurfaceScalarFieldNames when selecting scalar fields for computing min/max

File: gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx [hunk 4]
```diff
@@ -138,9 +139,9 @@ const WorkspaceViewMainWindow: FunctionComponent<Props> = ({data, selection, sel
         const visibleSurfaces = data.surfaces.filter(s => ((selection.visibleSurfaceNames || []).includes(s.name)))
         return visibleSurfaces.map(S => {
             const scalarFieldName = selection.selectedSurfaceScalarFieldNames[S.name]
-            const scalarField = scalarFieldName ? data.surfaceScalarFields.filter(x => (x.name === scalarFieldName))[0] : undefined
+            const scalarField = scalarFieldName ? data.surfaceScalarFields.filter(x => (x.name === scalarFieldName) && (x.surfaceName === S.name))[0] : undefined
             const vectorFieldName = selection.selectedSurfaceVectorFieldNames[S.name]
-            const vectorField = vectorFieldName ? data.surfaceVectorFields.filter(x => (x.name === vectorFieldName))[0] : undefined
+            const vectorField = vectorFieldName ? data.surfaceVectorFields.filter(x => (x.name === vectorFieldName) && (x.surfaceName === S.name))[0] : undefined
```
Comment (magland) [inline gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:144]: Use both surfaceName and name for selecting scalar/vector field for viewing.

File: gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx (hunk 3 above)
Comment (jsoules) [reply gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:85]: So to make sure I'm understanding this change: previously, when calibrating the range for values in a scalar field, we would pull a list of every surface scalar field name that was selected, and then pull the scalar fields corresponding to those names.

After the change, we pull the scalar fields satisfying the criteria: the selected-field-name of the surface this field belongs to, matches this field's name.

So the difference is in the first case, we're finding the range by looking at every field whose name matches a selection--whether it's selected on its corresponding surface or not--while after the change, we are only pulling those scalar fields which are selected on their surfaces.

Is that right?

Comment (magland) [reply gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:85]: Sort of but not quite. There was actually a bug in the old code. It was only finding the scalar fields with the given names and was not requiring the surfaceNames to match. So it was picking off the first field with the corresponding name, rather than the unique field with the corresponding name and surfaceName

Comment (jsoules) [reply gui/src/WorkspaceView/WorkspaceViewMainWindow.tsx:85]: Ah, okay, gotcha.

**Review by jsoules — APPROVED** [review]
I've read these changes and they make sense, but I don't have an example of the specific bug to test & confirm fix. But this does look good just from reading it.
